### ISSUE TITLE
Name change proposal

### ISSUE THREAD

**Issue by astrobokonon** [LowellObservatory/NightWatch#2]
Every time I see "NightWatchman" I think of ["Night Man"](https://www.youtube.com/watch?v=iJNtVNe286E) from It's Always Sunny in Philadelphia:

![image](https://user-images.githubusercontent.com/1168555/47385078-ea211600-d6bd-11e8-8bab-072fec87df78.png)

Maybe it's just me.  But NightWatch would work too and be a little shorter :smiley:

**Comment by dyerlytle** [comment]
It is fine with me.  I've not heard of "Night Man" so it never bothered me.  I also added a slightly different logo because Georgi said the one I had was "Creepy".  This is still in flux tho, I think the one on the home page is too complicated, logos should be simple.
