### ISSUE TITLE
Possible Themes for NightWatch

### ISSUE THREAD

**Issue by dyerlytle** [LowellObservatory/NightWatch#3]
There are a lot of themes out there.  Basically, all we need is an HTML theme and then just insert the various plots, images, info lists into the theme.

The [isotope](https://isotope.metafizzy.co/) theme, for example, looks interesting.

It looks nice but I don't know how it scales to smaller/larger formats, etc.

More research is needed, let me know what you come up with.

**Comment by dyerlytle** [comment]
[TemplateMonster](https://www.templatemonster.com) has a lot of ideas too.

**Comment by astrobokonon** [comment]
@dyerlytle I like the isotope one a lot.  The flexible different-sized-square nature of it seems like a pretty good fit for the initial test version.  The related [Packery](https://packery.metafizzy.co/) one lets you even drag and drop stuff around, though I kinda like how isotope tamed the infinite-tweakability of that with the filters + buttons.  

I'm still fuzzy on how they would actually interact and operate with something like django, but it would probably become clear with an example.

**Comment by dyerlytle** [comment]
I suspect as long as every piece of content on the NightWatch page is wrapped in a DIV, Isotope would  arrange them.

**Comment by astrobokonon** [comment]
Closing this since I think we've settled on something worthwhile for the alpha version.  Further comments on what we put together can be handled as a new issue.
